CREATE DATABASE IF NOT EXISTS couple_planner
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE couple_planner;

CREATE TABLE IF NOT EXISTS planners (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  data JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
